@startuml
hide footbox
skinparam shadowing false
title System Architecture Overview

actor User
participant ":Ui" as UI
participant ":Parser" as LOGIC
participant ":Model" as MODEL
participant ":Storage" as ST

User -> UI : "delete 1"
activate UI

UI -> LOGIC : parse & execute
activate LOGIC

LOGIC -> MODEL : update data
activate MODEL
MODEL --> LOGIC
deactivate MODEL

LOGIC -> ST : save data
activate ST
ST -> ST : write to file
ST --> LOGIC
deactivate ST

LOGIC --> UI
deactivate LOGIC

UI --> User : success message
deactivate UI
@enduml