@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam ArrowFontStyle normal

participant ":GradeCommand" as GradeCommand
participant "students:StudentList" as StudentList
participant "targetStudent:Student" as Student
participant "ui:Ui" as Ui

[-> GradeCommand : execute(students, ui)
activate GradeCommand

opt index valid
    GradeCommand -> StudentList : getActiveStudent(index - 1)
    activate StudentList
    StudentList --> GradeCommand : targetStudent
    deactivate StudentList

    GradeCommand -> Student : addGrade(assessment, score)
    activate Student
    deactivate Student

    GradeCommand -> Ui : showEditSuccess(targetStudent)
    activate Ui
    deactivate Ui
end

[<-- GradeCommand
deactivate GradeCommand
destroy GradeCommand
@enduml
