@startuml
hide footbox
skinparam ArrowFontStyle normal

participant ":TutorSwift" as TS
participant ":Parser" as Parser
participant ":DeleteCommand" as DC
participant "students:StudentList" as SL
participant "ui:Ui" as Ui

[-> TS : execute("delete 1")
activate TS

TS -> Parser : parseUserInput("delete 1")
activate Parser

create DC
Parser -> DC : DeleteCommand(index)
activate DC
Parser <-- DC :
deactivate DC

TS <-- Parser : deleteCommand
deactivate Parser

TS -> DC : execute(students, ui)
activate DC

alt invalid index
    DC --> TS : throws TutorSwiftException(message)
else valid index
    DC -> SL : getActiveStudent(0)
    activate SL
    SL --> DC : deletedStudent
    deactivate SL

    DC -> SL : deleteActiveStudent(0)
    activate SL
    SL --> DC :
    deactivate SL

    DC -> Ui : showDeleteSuccess(deletedStudent, students.getActiveSize())
    activate Ui
    Ui --> DC :
    deactivate Ui

    DC --> TS :
end

deactivate DC
destroy DC

deactivate TS
@enduml